### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by Musickiller** [fraction/oasis-desktop#30]
Hello!

I've tried Oasis, and encountered many problems with it.. The best one that's worked for me was git / master. However it had an issue that made it impossible to post new posts: when I've pressed "preview", it has shown me:
```
BadRequestError: Request must be addressed to 127.0.0.1 or localhost and non-GET requests must contain non-blob referer.
    at Object.assert (C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\http-assert\index.js:8:9)
    at C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\@fraction\oasis\src\http.js:107:9
    at dispatch (C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\koa-compose\index.js:42:32)
    at C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\koa-mount\index.js:52:32
    at dispatch (C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\koa-compose\index.js:42:32)
    at C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\koa\lib\application.js:168:12)
    at Server.handleRequest (C:\Users\dbobirev\apps\git\oasis-desktop\node_modules\koa\lib\application.js:150:19)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:790:12)
```
Has anyone also encountered this issue? I could not find it in github tracker. 

Kind Regards,
Dmitrii

**Comment by christianbundy** [comment]
Ahoy! What host are you trying to open Oasis on? Usually this happens when you try to access via some hostname that isn't `localhost`. If you need to access it via another host, try `oasis --host example.com`>

**Comment by Musickiller** [comment]
Strange thing is that I open it on my local machine with standard settings. So I don't suppose the host would be different.

**Comment by christianbundy** [comment]
What host are you trying to open Oasis on? http://localhost:3000 ?

**Comment by christianbundy** [comment]
If so, the only other thing is the referrer: Oasis ensures that when you submit a form you have to have a proper referrer. Any chance you're running some privacy software that blocks the referrer?

**Comment by Musickiller** [comment]
Referrer! Yeah, right. I have Toggle Referrer extension that blocks it on demand. And I forgot about it. Thanks a lot!

**Comment by christianbundy** [comment]
NP! Happy to have this fixed. 🚀
